### PR TITLE
Timer

### PR DESCRIPTION
**Pull request by redfieldstefan**

### CODE REVIEW

**Comment by andyjac** [comment]
I'm getting this after brewing a newly created recipe:

screen shot 2015-06-29 at 11 54 38 am

**Comment by redfieldstefan** [comment]
Weird, can you try building it again? It doesnt look like that at all
anymore, looks more like this

[image: Inline image 1]

On Mon, Jun 29, 2015 at 11:56 AM, Andrew <notifications@github.com> wrote:

> I'm getting this after brewing a newly created recipe:
>
> [image: screen shot 2015-06-29 at 11 54 38 am]
> <https://cloud.githubusercontent.com/assets/5609090/8415720/c7f3bf20-1e55-11e5-9533-26b73c7d2ad7.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redfieldstefan/brewtorial/pull/132#issuecomment-116796025>
> .
>



-- 
Stefan Redfield
www.stefanredfield.com

**Comment by andyjac** [comment]
Cool, re-built and it seems to be working better now. One small thing is that on the create recipe page in the results section It's showing the full objects like so:

screen shot 2015-06-29 at 12 12 00 pm

**Comment by redfieldstefan** [comment]
Aha! Nice. I will get that fixed in the next run.

On Mon, Jun 29, 2015 at 12:23 PM, Andrew <notifications@github.com> wrote:

> Cool, re-built and it seems to be working better now. One small thing is
> that on the create recipe page in the results section It's showing the full
> objects like so:
>
> [image: screen shot 2015-06-29 at 12 12 00 pm]
> <https://cloud.githubusercontent.com/assets/5609090/8416285/8c11e79e-1e59-11e5-9d50-831b82daf021.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redfieldstefan/brewtorial/pull/132#issuecomment-116803793>
> .
>



-- 
Stefan Redfield
www.stefanredfield.com

**Comment by andyjac** [comment]
Fixed.

**Pull request merged**
